name: Feature build

on:
  push:
    branches:
      - '*'
      - '!dev' 
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/nimo-labs/nimobuild:latest 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: 'bootloader'
        fetch-depth: 0

    - name: Compile
      run: |
        cd bootloader
        ./buildall.sh
